version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=3000
      # Add other environment variables here if needed
      # - STRAPI_API_URL=${STRAPI_API_URL}
      # - STRAPI_API_KEY=${STRAPI_API_KEY}
    restart: always
