
interface _GlobalComponents {
      'Barchart': typeof import("../components/global/Barchart.vue")['default']
    'CustomBarchart': typeof import("../components/global/CustomBarchart.vue")['default']
    'Footer': typeof import("../components/global/Footer.vue")['default']
    'MainButton': typeof import("../components/global/MainButton.vue")['default']
    'NavBar': typeof import("../components/global/NavBar.vue")['default']
    'FullLogo': typeof import("../components/global/fullLogo.vue")['default']
    'Pagination': typeof import("../components/global/pagination.vue")['default']
    'PieChart': typeof import("../components/global/pieChart.vue")['default']
    'Progressbar': typeof import("../components/global/progressbar.vue")['default']
    'Sublogo': typeof import("../components/global/sublogo.vue")['default']
    'CardConstitutionalNews': typeof import("../components/card/ConstitutionalNews.vue")['default']
    'CardNews': typeof import("../components/card/News.vue")['default']
    'CardAward': typeof import("../components/card/award.vue")['default']
    'CardEvent': typeof import("../components/card/event.vue")['default']
    'CardLegistlative': typeof import("../components/card/legistlative.vue")['default']
    'CardProject': typeof import("../components/card/project.vue")['default']
    'CardUpdates': typeof import("../components/card/updates.vue")['default']
    'ListEvents': typeof import("../components/list/events.vue")['default']
    'ModalsSubscribe': typeof import("../components/modals/Subscribe.vue")['default']
    'SectionsAbout': typeof import("../components/sections/About.vue")['default']
    'SectionsAboutLeadership': typeof import("../components/sections/AboutLeadership.vue")['default']
    'SectionsAboutMedia': typeof import("../components/sections/AboutMedia.vue")['default']
    'SectionsAboutQuotes': typeof import("../components/sections/AboutQuotes.vue")['default']
    'SectionsAccordion': typeof import("../components/sections/Accordion.vue")['default']
    'SectionsAccordionAlt': typeof import("../components/sections/AccordionAlt.vue")['default']
    'SectionsBigSlider': typeof import("../components/sections/BigSlider.vue")['default']
    'SectionsCarousel': typeof import("../components/sections/Carousel.vue")['default']
    'SectionsEvents': typeof import("../components/sections/Events.vue")['default']
    'SectionsFullPublications': typeof import("../components/sections/FullPublications.vue")['default']
    'SectionsHIstory': typeof import("../components/sections/HIstory.vue")['default']
    'SectionsHomeAbout': typeof import("../components/sections/HomeAbout.vue")['default']
    'SectionsManualSlider': typeof import("../components/sections/ManualSlider.vue")['default']
    'SectionsMedia': typeof import("../components/sections/Media.vue")['default']
    'SectionsNews': typeof import("../components/sections/News.vue")['default']
    'SectionsPublications': typeof import("../components/sections/Publications.vue")['default']
    'SectionsRoadMap': typeof import("../components/sections/RoadMap.vue")['default']
    'SectionsSlider': typeof import("../components/sections/Slider.vue")['default']
    'SectionsStatesman': typeof import("../components/sections/Statesman.vue")['default']
    'SectionsStats': typeof import("../components/sections/Stats.vue")['default']
    'SectionsTestimonial': typeof import("../components/sections/Testimonial.vue")['default']
    'SectionsUpdates': typeof import("../components/sections/Updates.vue")['default']
    'SectionsAboutDropDown': typeof import("../components/sections/aboutDropDown.vue")['default']
    'SectionsBillsDropDown': typeof import("../components/sections/billsDropDown.vue")['default']
    'SectionsContact': typeof import("../components/sections/contact.vue")['default']
    'SectionsFaq': typeof import("../components/sections/faq.vue")['default']
    'SectionsFeaturedProject': typeof import("../components/sections/featuredProject.vue")['default']
    'SectionsLatestNews': typeof import("../components/sections/latestNews.vue")['default']
    'SectionsLegistlativeDropDown': typeof import("../components/sections/legistlativeDropDown.vue")['default']
    'SectionsPortal': typeof import("../components/sections/portal.vue")['default']
    'SectionsProjectsDropDown': typeof import("../components/sections/projectsDropDown.vue")['default']
    'SectionsReview': typeof import("../components/sections/review.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtImg': typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-img")['default']
    'NuxtPicture': typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-picture")['default']
    'SvgIcon': typeof import("../node_modules/@nuxtjs/svg-sprite/dist/runtime/components/svg-icon.vue")['default']
    'Swiper': typeof import("swiper/vue")['Swiper']
    'SwiperSlide': typeof import("swiper/vue")['SwiperSlide']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
      'LazyBarchart': typeof import("../components/global/Barchart.vue")['default']
    'LazyCustomBarchart': typeof import("../components/global/CustomBarchart.vue")['default']
    'LazyFooter': typeof import("../components/global/Footer.vue")['default']
    'LazyMainButton': typeof import("../components/global/MainButton.vue")['default']
    'LazyNavBar': typeof import("../components/global/NavBar.vue")['default']
    'LazyFullLogo': typeof import("../components/global/fullLogo.vue")['default']
    'LazyPagination': typeof import("../components/global/pagination.vue")['default']
    'LazyPieChart': typeof import("../components/global/pieChart.vue")['default']
    'LazyProgressbar': typeof import("../components/global/progressbar.vue")['default']
    'LazySublogo': typeof import("../components/global/sublogo.vue")['default']
    'LazyCardConstitutionalNews': typeof import("../components/card/ConstitutionalNews.vue")['default']
    'LazyCardNews': typeof import("../components/card/News.vue")['default']
    'LazyCardAward': typeof import("../components/card/award.vue")['default']
    'LazyCardEvent': typeof import("../components/card/event.vue")['default']
    'LazyCardLegistlative': typeof import("../components/card/legistlative.vue")['default']
    'LazyCardProject': typeof import("../components/card/project.vue")['default']
    'LazyCardUpdates': typeof import("../components/card/updates.vue")['default']
    'LazyListEvents': typeof import("../components/list/events.vue")['default']
    'LazyModalsSubscribe': typeof import("../components/modals/Subscribe.vue")['default']
    'LazySectionsAbout': typeof import("../components/sections/About.vue")['default']
    'LazySectionsAboutLeadership': typeof import("../components/sections/AboutLeadership.vue")['default']
    'LazySectionsAboutMedia': typeof import("../components/sections/AboutMedia.vue")['default']
    'LazySectionsAboutQuotes': typeof import("../components/sections/AboutQuotes.vue")['default']
    'LazySectionsAccordion': typeof import("../components/sections/Accordion.vue")['default']
    'LazySectionsAccordionAlt': typeof import("../components/sections/AccordionAlt.vue")['default']
    'LazySectionsBigSlider': typeof import("../components/sections/BigSlider.vue")['default']
    'LazySectionsCarousel': typeof import("../components/sections/Carousel.vue")['default']
    'LazySectionsEvents': typeof import("../components/sections/Events.vue")['default']
    'LazySectionsFullPublications': typeof import("../components/sections/FullPublications.vue")['default']
    'LazySectionsHIstory': typeof import("../components/sections/HIstory.vue")['default']
    'LazySectionsHomeAbout': typeof import("../components/sections/HomeAbout.vue")['default']
    'LazySectionsManualSlider': typeof import("../components/sections/ManualSlider.vue")['default']
    'LazySectionsMedia': typeof import("../components/sections/Media.vue")['default']
    'LazySectionsNews': typeof import("../components/sections/News.vue")['default']
    'LazySectionsPublications': typeof import("../components/sections/Publications.vue")['default']
    'LazySectionsRoadMap': typeof import("../components/sections/RoadMap.vue")['default']
    'LazySectionsSlider': typeof import("../components/sections/Slider.vue")['default']
    'LazySectionsStatesman': typeof import("../components/sections/Statesman.vue")['default']
    'LazySectionsStats': typeof import("../components/sections/Stats.vue")['default']
    'LazySectionsTestimonial': typeof import("../components/sections/Testimonial.vue")['default']
    'LazySectionsUpdates': typeof import("../components/sections/Updates.vue")['default']
    'LazySectionsAboutDropDown': typeof import("../components/sections/aboutDropDown.vue")['default']
    'LazySectionsBillsDropDown': typeof import("../components/sections/billsDropDown.vue")['default']
    'LazySectionsContact': typeof import("../components/sections/contact.vue")['default']
    'LazySectionsFaq': typeof import("../components/sections/faq.vue")['default']
    'LazySectionsFeaturedProject': typeof import("../components/sections/featuredProject.vue")['default']
    'LazySectionsLatestNews': typeof import("../components/sections/latestNews.vue")['default']
    'LazySectionsLegistlativeDropDown': typeof import("../components/sections/legistlativeDropDown.vue")['default']
    'LazySectionsPortal': typeof import("../components/sections/portal.vue")['default']
    'LazySectionsProjectsDropDown': typeof import("../components/sections/projectsDropDown.vue")['default']
    'LazySectionsReview': typeof import("../components/sections/review.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtImg': typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-img")['default']
    'LazyNuxtPicture': typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-picture")['default']
    'LazySvgIcon': typeof import("../node_modules/@nuxtjs/svg-sprite/dist/runtime/components/svg-icon.vue")['default']
    'LazySwiper': typeof import("swiper/vue")['Swiper']
    'LazySwiperSlide': typeof import("swiper/vue")['SwiperSlide']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const Barchart: typeof import("../components/global/Barchart.vue")['default']
export const CustomBarchart: typeof import("../components/global/CustomBarchart.vue")['default']
export const Footer: typeof import("../components/global/Footer.vue")['default']
export const MainButton: typeof import("../components/global/MainButton.vue")['default']
export const NavBar: typeof import("../components/global/NavBar.vue")['default']
export const FullLogo: typeof import("../components/global/fullLogo.vue")['default']
export const Pagination: typeof import("../components/global/pagination.vue")['default']
export const PieChart: typeof import("../components/global/pieChart.vue")['default']
export const Progressbar: typeof import("../components/global/progressbar.vue")['default']
export const Sublogo: typeof import("../components/global/sublogo.vue")['default']
export const CardConstitutionalNews: typeof import("../components/card/ConstitutionalNews.vue")['default']
export const CardNews: typeof import("../components/card/News.vue")['default']
export const CardAward: typeof import("../components/card/award.vue")['default']
export const CardEvent: typeof import("../components/card/event.vue")['default']
export const CardLegistlative: typeof import("../components/card/legistlative.vue")['default']
export const CardProject: typeof import("../components/card/project.vue")['default']
export const CardUpdates: typeof import("../components/card/updates.vue")['default']
export const ListEvents: typeof import("../components/list/events.vue")['default']
export const ModalsSubscribe: typeof import("../components/modals/Subscribe.vue")['default']
export const SectionsAbout: typeof import("../components/sections/About.vue")['default']
export const SectionsAboutLeadership: typeof import("../components/sections/AboutLeadership.vue")['default']
export const SectionsAboutMedia: typeof import("../components/sections/AboutMedia.vue")['default']
export const SectionsAboutQuotes: typeof import("../components/sections/AboutQuotes.vue")['default']
export const SectionsAccordion: typeof import("../components/sections/Accordion.vue")['default']
export const SectionsAccordionAlt: typeof import("../components/sections/AccordionAlt.vue")['default']
export const SectionsBigSlider: typeof import("../components/sections/BigSlider.vue")['default']
export const SectionsCarousel: typeof import("../components/sections/Carousel.vue")['default']
export const SectionsEvents: typeof import("../components/sections/Events.vue")['default']
export const SectionsFullPublications: typeof import("../components/sections/FullPublications.vue")['default']
export const SectionsHIstory: typeof import("../components/sections/HIstory.vue")['default']
export const SectionsHomeAbout: typeof import("../components/sections/HomeAbout.vue")['default']
export const SectionsManualSlider: typeof import("../components/sections/ManualSlider.vue")['default']
export const SectionsMedia: typeof import("../components/sections/Media.vue")['default']
export const SectionsNews: typeof import("../components/sections/News.vue")['default']
export const SectionsPublications: typeof import("../components/sections/Publications.vue")['default']
export const SectionsRoadMap: typeof import("../components/sections/RoadMap.vue")['default']
export const SectionsSlider: typeof import("../components/sections/Slider.vue")['default']
export const SectionsStatesman: typeof import("../components/sections/Statesman.vue")['default']
export const SectionsStats: typeof import("../components/sections/Stats.vue")['default']
export const SectionsTestimonial: typeof import("../components/sections/Testimonial.vue")['default']
export const SectionsUpdates: typeof import("../components/sections/Updates.vue")['default']
export const SectionsAboutDropDown: typeof import("../components/sections/aboutDropDown.vue")['default']
export const SectionsBillsDropDown: typeof import("../components/sections/billsDropDown.vue")['default']
export const SectionsContact: typeof import("../components/sections/contact.vue")['default']
export const SectionsFaq: typeof import("../components/sections/faq.vue")['default']
export const SectionsFeaturedProject: typeof import("../components/sections/featuredProject.vue")['default']
export const SectionsLatestNews: typeof import("../components/sections/latestNews.vue")['default']
export const SectionsLegistlativeDropDown: typeof import("../components/sections/legistlativeDropDown.vue")['default']
export const SectionsPortal: typeof import("../components/sections/portal.vue")['default']
export const SectionsProjectsDropDown: typeof import("../components/sections/projectsDropDown.vue")['default']
export const SectionsReview: typeof import("../components/sections/review.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-img")['default']
export const NuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-picture")['default']
export const SvgIcon: typeof import("../node_modules/@nuxtjs/svg-sprite/dist/runtime/components/svg-icon.vue")['default']
export const Swiper: typeof import("swiper/vue")['Swiper']
export const SwiperSlide: typeof import("swiper/vue")['SwiperSlide']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyBarchart: typeof import("../components/global/Barchart.vue")['default']
export const LazyCustomBarchart: typeof import("../components/global/CustomBarchart.vue")['default']
export const LazyFooter: typeof import("../components/global/Footer.vue")['default']
export const LazyMainButton: typeof import("../components/global/MainButton.vue")['default']
export const LazyNavBar: typeof import("../components/global/NavBar.vue")['default']
export const LazyFullLogo: typeof import("../components/global/fullLogo.vue")['default']
export const LazyPagination: typeof import("../components/global/pagination.vue")['default']
export const LazyPieChart: typeof import("../components/global/pieChart.vue")['default']
export const LazyProgressbar: typeof import("../components/global/progressbar.vue")['default']
export const LazySublogo: typeof import("../components/global/sublogo.vue")['default']
export const LazyCardConstitutionalNews: typeof import("../components/card/ConstitutionalNews.vue")['default']
export const LazyCardNews: typeof import("../components/card/News.vue")['default']
export const LazyCardAward: typeof import("../components/card/award.vue")['default']
export const LazyCardEvent: typeof import("../components/card/event.vue")['default']
export const LazyCardLegistlative: typeof import("../components/card/legistlative.vue")['default']
export const LazyCardProject: typeof import("../components/card/project.vue")['default']
export const LazyCardUpdates: typeof import("../components/card/updates.vue")['default']
export const LazyListEvents: typeof import("../components/list/events.vue")['default']
export const LazyModalsSubscribe: typeof import("../components/modals/Subscribe.vue")['default']
export const LazySectionsAbout: typeof import("../components/sections/About.vue")['default']
export const LazySectionsAboutLeadership: typeof import("../components/sections/AboutLeadership.vue")['default']
export const LazySectionsAboutMedia: typeof import("../components/sections/AboutMedia.vue")['default']
export const LazySectionsAboutQuotes: typeof import("../components/sections/AboutQuotes.vue")['default']
export const LazySectionsAccordion: typeof import("../components/sections/Accordion.vue")['default']
export const LazySectionsAccordionAlt: typeof import("../components/sections/AccordionAlt.vue")['default']
export const LazySectionsBigSlider: typeof import("../components/sections/BigSlider.vue")['default']
export const LazySectionsCarousel: typeof import("../components/sections/Carousel.vue")['default']
export const LazySectionsEvents: typeof import("../components/sections/Events.vue")['default']
export const LazySectionsFullPublications: typeof import("../components/sections/FullPublications.vue")['default']
export const LazySectionsHIstory: typeof import("../components/sections/HIstory.vue")['default']
export const LazySectionsHomeAbout: typeof import("../components/sections/HomeAbout.vue")['default']
export const LazySectionsManualSlider: typeof import("../components/sections/ManualSlider.vue")['default']
export const LazySectionsMedia: typeof import("../components/sections/Media.vue")['default']
export const LazySectionsNews: typeof import("../components/sections/News.vue")['default']
export const LazySectionsPublications: typeof import("../components/sections/Publications.vue")['default']
export const LazySectionsRoadMap: typeof import("../components/sections/RoadMap.vue")['default']
export const LazySectionsSlider: typeof import("../components/sections/Slider.vue")['default']
export const LazySectionsStatesman: typeof import("../components/sections/Statesman.vue")['default']
export const LazySectionsStats: typeof import("../components/sections/Stats.vue")['default']
export const LazySectionsTestimonial: typeof import("../components/sections/Testimonial.vue")['default']
export const LazySectionsUpdates: typeof import("../components/sections/Updates.vue")['default']
export const LazySectionsAboutDropDown: typeof import("../components/sections/aboutDropDown.vue")['default']
export const LazySectionsBillsDropDown: typeof import("../components/sections/billsDropDown.vue")['default']
export const LazySectionsContact: typeof import("../components/sections/contact.vue")['default']
export const LazySectionsFaq: typeof import("../components/sections/faq.vue")['default']
export const LazySectionsFeaturedProject: typeof import("../components/sections/featuredProject.vue")['default']
export const LazySectionsLatestNews: typeof import("../components/sections/latestNews.vue")['default']
export const LazySectionsLegistlativeDropDown: typeof import("../components/sections/legistlativeDropDown.vue")['default']
export const LazySectionsPortal: typeof import("../components/sections/portal.vue")['default']
export const LazySectionsProjectsDropDown: typeof import("../components/sections/projectsDropDown.vue")['default']
export const LazySectionsReview: typeof import("../components/sections/review.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-img")['default']
export const LazyNuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-picture")['default']
export const LazySvgIcon: typeof import("../node_modules/@nuxtjs/svg-sprite/dist/runtime/components/svg-icon.vue")['default']
export const LazySwiper: typeof import("swiper/vue")['Swiper']
export const LazySwiperSlide: typeof import("swiper/vue")['SwiperSlide']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']

export const componentNames: string[]
