// Generated by @nuxtjs/svg-sprite
export const sprites = {
  "icons": () => import("/Users/mac/Documents/Work/Govtech/Benjamin_Kalu/benjamin_kalu_website/assets/sprite/gen/icons.svg").then(r => r.default || r)
}
export const spriteClass = "";

export const spriteClassPrefix = "";

export const defaultSprite = "icons";
