// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 7/27/2026, 1:42:38 PM
const configMerger = require("/Users/mac/Documents/Work/Govtech/Benjamin_Kalu/benjamin_kalu_website/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/mac/Documents/Work/Govtech/Benjamin_Kalu/benjamin_kalu_website/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Documents/Work/Govtech/Benjamin_Kalu/benjamin_kalu_website/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Documents/Work/Govtech/Benjamin_Kalu/benjamin_kalu_website/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Documents/Work/Govtech/Benjamin_Kalu/benjamin_kalu_website/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Documents/Work/Govtech/Benjamin_Kalu/benjamin_kalu_website/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Documents/Work/Govtech/Benjamin_Kalu/benjamin_kalu_website/plugins/**/*.{js,ts,mjs}","/Users/mac/Documents/Work/Govtech/Benjamin_Kalu/benjamin_kalu_website/composables/**/*.{js,ts,mjs}","/Users/mac/Documents/Work/Govtech/Benjamin_Kalu/benjamin_kalu_website/utils/**/*.{js,ts,mjs}","/Users/mac/Documents/Work/Govtech/Benjamin_Kalu/benjamin_kalu_website/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Documents/Work/Govtech/Benjamin_Kalu/benjamin_kalu_website/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Documents/Work/Govtech/Benjamin_Kalu/benjamin_kalu_website/app.config.{js,ts,mjs}"] }));

module.exports = config
